USE proyecto_4_sql;

-- PASO 1: LIMPIEZA FORZADA Y CORRECCIONES DE ESTRUCTURA

-- 1. DESACTIVAR COMPROBACIONES DE FK (Para forzar la limpieza)
SET FOREIGN_KEY_CHECKS = 0;

-- 2. AJUSTAR TAMAÑO DE COLUMNAS (Para prevenir Error 1406, usando TEXT)
ALTER TABLE actors MODIFY COLUMN cast_name TEXT NOT NULL;
ALTER TABLE directors MODIFY COLUMN director_name TEXT NOT NULL;

-- 3. VACIAR TODAS LAS TABLAS EN ORDEN SEGURO
TRUNCATE TABLE title_cast;
TRUNCATE TABLE title_director;
TRUNCATE TABLE title_genre;
TRUNCATE TABLE title_country;
TRUNCATE TABLE titles;
TRUNCATE TABLE actors;
TRUNCATE TABLE directors;
TRUNCATE TABLE genres;
TRUNCATE TABLE countries;
TRUNCATE TABLE release_years;
TRUNCATE TABLE types;
TRUNCATE TABLE platforms;

-- 4. REACTIVAR COMPROBACIONES DE FK
SET FOREIGN_KEY_CHECKS = 1;

-- PASO 2: CARGA DE DATOS (Con Rutas Literales)

-- Ruta segura para cada tabla.
SET @UPLOAD_PATH = 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/'; 

-- BLOQUE A: CARGA DE TABLAS DE REFERENCIA 

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/actores.csv' 
INTO TABLE actors
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/directores.csv' 
INTO TABLE directors
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/genero.csv' 
INTO TABLE genres
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/pais.csv' 
INTO TABLE countries
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE "C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/year_unicos.csv" 
INTO TABLE release_years
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/tipos.csv' 
INTO TABLE types
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE "C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/plataforma.csv"
INTO TABLE platforms
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


-- BLOQUE B: CARGA DE LA TABLA PRINCIPAL

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/tabla_titles.csv' 
INTO TABLE titles
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


-- BLOQUE C: CARGA DE TABLAS PUENTE 

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/show_actor.csv' 
INTO TABLE title_cast
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/show_director.csv' 
INTO TABLE title_director
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/show_genre.csv' 
INTO TABLE title_genre
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/show_country.csv' 
INTO TABLE title_country
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Revisión rápida de datos cargados
SELECT 
    (SELECT COUNT(*) FROM actors) AS Total_Actores,
    (SELECT COUNT(*) FROM directors) AS Total_Directores,
    (SELECT COUNT(*) FROM titles) AS Total_Titulos,
    (SELECT COUNT(*) FROM title_cast) AS Total_Relaciones_Cast;